name: Publish Package

on:
  push:
    branches:
      - master   # or master, adjust as needed
    # You can also add tags if you want to publish on tag creation

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com/

      - name: Authenticate to GitHub Packages npm registry
        run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Publish package
        run: npm publish
